// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package cache

type AgentCache struct {
	ID            int64  `json:"id"`
	Url           string `json:"url"`
	ParserType    string `json:"parser_type"`
	AgentPipeline string `json:"agent_pipeline"`
	OutputData    string `json:"output_data"`
	CreatedAt     int64  `json:"created_at"`
	AccessedAt    int64  `json:"accessed_at"`
}

type ParserCache struct {
	ID         int64  `json:"id"`
	Url        string `json:"url"`
	ParserType string `json:"parser_type"`
	OutputData string `json:"output_data"`
	CreatedAt  int64  `json:"created_at"`
	AccessedAt int64  `json:"accessed_at"`
}
