// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package cache

import (
	"context"
)

const countAgentEntries = `-- name: CountAgentEntries :one
SELECT COUNT(*) FROM agent_cache
`

func (q *Queries) CountAgentEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgentEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countParserEntries = `-- name: CountParserEntries :one
SELECT COUNT(*) FROM parser_cache
`

func (q *Queries) CountParserEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countParserEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAgentCache = `-- name: DeleteAgentCache :exec
DELETE FROM agent_cache
`

func (q *Queries) DeleteAgentCache(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAgentCache)
	return err
}

const deleteParserCache = `-- name: DeleteParserCache :exec
DELETE FROM parser_cache
`

func (q *Queries) DeleteParserCache(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteParserCache)
	return err
}

const getAgentOutput = `-- name: GetAgentOutput :one

SELECT output_data
FROM agent_cache
WHERE url = ? AND parser_type = ? AND agent_pipeline = ?
`

type GetAgentOutputParams struct {
	Url           string `json:"url"`
	ParserType    string `json:"parser_type"`
	AgentPipeline string `json:"agent_pipeline"`
}

// Agent Cache Queries
func (q *Queries) GetAgentOutput(ctx context.Context, arg GetAgentOutputParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getAgentOutput, arg.Url, arg.ParserType, arg.AgentPipeline)
	var output_data string
	err := row.Scan(&output_data)
	return output_data, err
}

const getOldestCacheEntry = `-- name: GetOldestCacheEntry :one

SELECT MIN(created_at) as oldest
FROM (
    SELECT created_at FROM parser_cache
    UNION ALL
    SELECT created_at FROM agent_cache
)
`

// Statistics Queries
func (q *Queries) GetOldestCacheEntry(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getOldestCacheEntry)
	var oldest interface{}
	err := row.Scan(&oldest)
	return oldest, err
}

const getParserOutput = `-- name: GetParserOutput :one

SELECT output_data
FROM parser_cache
WHERE url = ? AND parser_type = ?
`

type GetParserOutputParams struct {
	Url        string `json:"url"`
	ParserType string `json:"parser_type"`
}

// Parser Cache Queries
func (q *Queries) GetParserOutput(ctx context.Context, arg GetParserOutputParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getParserOutput, arg.Url, arg.ParserType)
	var output_data string
	err := row.Scan(&output_data)
	return output_data, err
}

const setAgentOutput = `-- name: SetAgentOutput :exec
INSERT OR REPLACE INTO agent_cache
(url, parser_type, agent_pipeline, output_data, created_at, accessed_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type SetAgentOutputParams struct {
	Url           string `json:"url"`
	ParserType    string `json:"parser_type"`
	AgentPipeline string `json:"agent_pipeline"`
	OutputData    string `json:"output_data"`
	CreatedAt     int64  `json:"created_at"`
	AccessedAt    int64  `json:"accessed_at"`
}

func (q *Queries) SetAgentOutput(ctx context.Context, arg SetAgentOutputParams) error {
	_, err := q.db.ExecContext(ctx, setAgentOutput,
		arg.Url,
		arg.ParserType,
		arg.AgentPipeline,
		arg.OutputData,
		arg.CreatedAt,
		arg.AccessedAt,
	)
	return err
}

const setParserOutput = `-- name: SetParserOutput :exec
INSERT OR REPLACE INTO parser_cache
(url, parser_type, output_data, created_at, accessed_at)
VALUES (?, ?, ?, ?, ?)
`

type SetParserOutputParams struct {
	Url        string `json:"url"`
	ParserType string `json:"parser_type"`
	OutputData string `json:"output_data"`
	CreatedAt  int64  `json:"created_at"`
	AccessedAt int64  `json:"accessed_at"`
}

func (q *Queries) SetParserOutput(ctx context.Context, arg SetParserOutputParams) error {
	_, err := q.db.ExecContext(ctx, setParserOutput,
		arg.Url,
		arg.ParserType,
		arg.OutputData,
		arg.CreatedAt,
		arg.AccessedAt,
	)
	return err
}

const updateAgentAccessTime = `-- name: UpdateAgentAccessTime :exec
UPDATE agent_cache
SET accessed_at = ?
WHERE url = ? AND parser_type = ? AND agent_pipeline = ?
`

type UpdateAgentAccessTimeParams struct {
	AccessedAt    int64  `json:"accessed_at"`
	Url           string `json:"url"`
	ParserType    string `json:"parser_type"`
	AgentPipeline string `json:"agent_pipeline"`
}

func (q *Queries) UpdateAgentAccessTime(ctx context.Context, arg UpdateAgentAccessTimeParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentAccessTime,
		arg.AccessedAt,
		arg.Url,
		arg.ParserType,
		arg.AgentPipeline,
	)
	return err
}

const updateParserAccessTime = `-- name: UpdateParserAccessTime :exec
UPDATE parser_cache
SET accessed_at = ?
WHERE url = ? AND parser_type = ?
`

type UpdateParserAccessTimeParams struct {
	AccessedAt int64  `json:"accessed_at"`
	Url        string `json:"url"`
	ParserType string `json:"parser_type"`
}

func (q *Queries) UpdateParserAccessTime(ctx context.Context, arg UpdateParserAccessTimeParams) error {
	_, err := q.db.ExecContext(ctx, updateParserAccessTime, arg.AccessedAt, arg.Url, arg.ParserType)
	return err
}
