// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type AgentCache struct {
	ID            int64
	Url           string
	ParserType    string
	AgentPipeline string
	OutputData    string
	CreatedAt     int64
	AccessedAt    int64
}

type Feed struct {
	Url             string
	Title           string
	LastProcessedAt int64
}

type GenerationHistory struct {
	ID              int64
	FeedUrl         string
	LastProcessedAt int64
	CreatedAt       int64
}

type ParserCache struct {
	ID         int64
	Url        string
	ParserType string
	OutputData string
	CreatedAt  int64
	AccessedAt int64
}
