// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getFeed = `-- name: GetFeed :one
SELECT url, title, last_processed_at
FROM feed
WHERE url = ?
`

func (q *Queries) GetFeed(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, url)
	var i Feed
	err := row.Scan(&i.Url, &i.Title, &i.LastProcessedAt)
	return i, err
}

const updateLastProcessedAt = `-- name: UpdateLastProcessedAt :exec
INSERT OR REPLACE INTO feed (url, title, last_processed_at)
VALUES (?, ?, ?)
`

type UpdateLastProcessedAtParams struct {
	Url             string
	Title           string
	LastProcessedAt int64
}

func (q *Queries) UpdateLastProcessedAt(ctx context.Context, arg UpdateLastProcessedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateLastProcessedAt, arg.Url, arg.Title, arg.LastProcessedAt)
	return err
}
